name: CI/CD Pipeline

on:
 
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: node js 
      uses: action/setup-node@v3
      with:
       version: '20'
    - name  : Install Dependence
      run : npm i
    # - name : prisma 
    #   uses  : npm run db:generate 
    - name : Build
      run: npm run build  



    