name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

   
    - name: Run Prisma Generate
      run: npm run db:generate




    - name: Build the project
      run: npm run build
